// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParkingApp.Pages;

#nullable disable

namespace ParkingApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250116101007_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.36");

            modelBuilder.Entity("ParkingApp.Pages.Parking", b =>
                {
                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ParkingTime")
                        .HasColumnType("TEXT");

                    b.ToTable("Parking");
                });
#pragma warning restore 612, 618
        }
    }
}
